baseurl = "/"
title = "Search and Learn"
copyright = "&copy; aram.com 2018"
theme = "searchnlearn"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 10
disqusShortname = ""
googleAnalytics = ""
defaultContentLanguage = "en"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false
enableGitInfo = false

[outputs]
home = ["HTML", "CSS", "RSS", "JSON"]
section = ["HTML", "RSS"]

[blackfriday]
fractions = true
hrefTargetBlank = true
smartypants = true

[params]
address = "Building 1 Room 1, Stanford University, California, 90210, USA"
avatar = "portrait.jpg"
color_theme = "default"
comment_count = true
custom_css = []
custom_js = []
date_format = "Jan 2, 2006"
email = "test@example.org"
font = "default"
gravatar = false
highlight = true
highlight_languages = []
keybase = ""
latitude = "37.4275"
logo = ""
longitude = "-122.1697"
map = 0
map_api_key = ""
math = false
name = "Sathish Kumar"
office_hours = "  Monday 10:00 to 13:00Wednesday 09:00 to 10:00Otherwise email to book an appointment\n  "
phone = "888 888 88 88"
privacy_pack = false
publication_types = ["Uncategorized", "Conference paper", "Journal article", "Manuscript", "Report", "Book", "Book section"]
reading_time = true
role = "Founder"
section_pager = false
sharing = true
skype = "echo123"
telegram = ""
time_format = "3:04 PM"
zoom = 15

[params.menus]
align_right = true

[[params.organizations]]
name = "Aram"
url = ""

[params.projects]
list_children = true
publication_format = 4

[[params.social]]
icon = "envelope"
icon_pack = "fas"
link = "#contact"

[[params.social]]
icon = "twitter"
icon_pack = "fab"
link = "https://twitter.com/rockyxsalt"

[[params.social]]
icon = "google-scholar"
icon_pack = "ai"
link = "https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ"

[[params.social]]
icon = "github"
icon_pack = "fab"
link = "https://github.com/gcushen"

[params.talks]
time = true

[menu]

[[menu.main]]
name = "Home"
url = "#about"
weight = 1

[[menu.main]]
name = "Publications"
url = "#publications_selected"
weight = 2

[[menu.main]]
name = "Posts"
url = "#posts"
weight = 3

[[menu.main]]
name = "Projects"
url = "#projects"
weight = 4

[[menu.main]]
name = "Tutorials"
url = "/tutorial/"
weight = 5

[[menu.main]]
name = "Contact"
url = "#contact"
weight = 6

[taxonomies]
category = "categories"
publication_type = "publication_types"
tag = "tags"

[Languages]

[Languages.en]
languageCode = "English"